# -*- coding: utf-8 -*-
import sys, \
    os
if hasattr(sys, 'frozen'):
    os.environ['PATH'] = sys._MEIPASS + ";" + os.environ['PATH']

from PyQt5.QtWidgets import QWidget, QLabel, QHBoxLayout, QGroupBox, QGridLayout, QLineEdit, QPushButton, QTextBrowser, QCheckBox, QComboBox, QVBoxLayout
from PyQt5.QtGui import QFont, QPixmap, QPalette, QColor, QCursor, QBrush
from PyQt5.QtCore import QRect, Qt, QMetaObject, QCoreApplication

from linkSHUPath import shuPath
from timg_png import img as timg
import base64


linkpath = shuPath()

sss = os.path.exists(linkpath + r'\timg.png')
if not sss:
    tmp = open(linkpath + r'\timg.png', 'wb')
    tmp.write(base64.b64decode(timg))
    tmp.close()
else:
    pass


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(433, 291)
        font = QFont()
        font.setPointSize(11)
        MainWindow.setFont(font)

        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QRect(10, 70, 231, 131))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget = QWidget(self.groupBox)
        self.gridLayoutWidget.setGeometry(QRect(9, 10, 213, 91))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.input_user = QLineEdit(self.gridLayoutWidget)
        font = QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.input_user.setFont(font)
        self.input_user.setText("")
        self.input_user.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.input_user.setObjectName("input_user")
        self.gridLayout.addWidget(self.input_user, 0, 1, 1, 1)
        self.user = QLabel(self.gridLayoutWidget)
        font = QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.user.setFont(font)
        self.user.setAlignment(Qt.AlignCenter)
        self.user.setObjectName("user")
        self.gridLayout.addWidget(self.user, 0, 0, 1, 1)
        self.input_passwd = QLineEdit(self.gridLayoutWidget)
        font = QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.input_passwd.setFont(font)
        self.input_passwd.setFocusPolicy(Qt.StrongFocus)
        self.input_passwd.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.input_passwd.setText("")
        self.input_passwd.setEchoMode(QLineEdit.Password)
        self.input_passwd.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.input_passwd.setObjectName("input_passwd")
        self.gridLayout.addWidget(self.input_passwd, 1, 1, 1, 1)
        self.passwd = QLabel(self.gridLayoutWidget)
        font = QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.passwd.setFont(font)
        self.passwd.setAlignment(Qt.AlignCenter)
        self.passwd.setObjectName("passwd")
        self.gridLayout.addWidget(self.passwd, 1, 0, 1, 1)
        self.horizontalLayoutWidget = QWidget(self.groupBox)
        self.horizontalLayoutWidget.setGeometry(QRect(10, 102, 211, 26))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_7 = QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.passwdCB = QCheckBox(self.horizontalLayoutWidget)
        font = QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.passwdCB.setFont(font)
        self.passwdCB.setObjectName("passwdCB")
        self.horizontalLayout_7.addWidget(self.passwdCB)
        self.auto_login = QCheckBox(self.horizontalLayoutWidget)
        font = QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.auto_login.setFont(font)
        self.auto_login.setObjectName("auto_login")
        self.horizontalLayout_7.addWidget(self.auto_login)
        self.groupBox_2 = QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QRect(240, 70, 181, 131))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayoutWidget = QWidget(self.groupBox_2)
        self.verticalLayoutWidget.setGeometry(QRect(10, 10, 161, 111))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.status_lable = QLabel(self.verticalLayoutWidget)
        font = QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.status_lable.setFont(font)
        self.status_lable.setAlignment(Qt.AlignCenter)
        self.status_lable.setObjectName("status_lable")
        self.verticalLayout.addWidget(self.status_lable)
        self.status = QTextBrowser(self.verticalLayoutWidget)
        font = QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.status.setFont(font)
        self.status.setObjectName("status")
        self.verticalLayout.addWidget(self.status)
        self.groupBox_3 = QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QRect(10, 250, 411, 31))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.updateLabel = QLabel(self.groupBox_3)
        self.updateLabel.setGeometry(QRect(150, 0, 111, 31))
        font = QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.updateLabel.setFont(font)
        self.updateLabel.setCursor(QCursor(Qt.PointingHandCursor))
        self.updateLabel.setToolTip("")
        self.updateLabel.setAlignment(Qt.AlignCenter)
        self.updateLabel.setObjectName("updateLabel")
        self.groupBox_4 = QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QRect(10, 0, 411, 71))
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.logo = QLabel(self.groupBox_4)
        self.logo.setGeometry(QRect(80, 10, 250, 51))
        self.logo.setText("")
        self.logo.setPixmap(QPixmap(linkpath + r'\timg.png'))
        self.logo.setObjectName("logo")
        self.text = QLabel(self.groupBox_4)
        self.text.setGeometry(QRect(180, 10, 122, 49))
        palette = QPalette()
        brush = QBrush(QColor(0, 85, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        brush = QBrush(QColor(0, 85, 255, 128))
        brush.setStyle(Qt.NoBrush)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush)
        brush = QBrush(QColor(0, 85, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush)
        brush = QBrush(QColor(0, 85, 255, 128))
        brush.setStyle(Qt.NoBrush)
        palette.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush)
        brush = QBrush(QColor(120, 120, 120))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush)
        brush = QBrush(QColor(0, 85, 255, 128))
        brush.setStyle(Qt.NoBrush)
        palette.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush)
        self.text.setPalette(palette)
        font = QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.text.setFont(font)
        self.text.setAlignment(Qt.AlignCenter)
        self.text.setObjectName("text")
        self.groupBox_5 = QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QRect(240, 200, 181, 51))
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.login = QPushButton(self.groupBox_5)
        self.login.setGeometry(QRect(10, 10, 91, 28))
        font = QFont()
        font.setFamily("微软雅黑")
        self.login.setFont(font)
        self.login.setObjectName("login")
        self.logout = QPushButton(self.groupBox_5)
        self.logout.setGeometry(QRect(110, 10, 61, 28))
        font = QFont()
        font.setFamily("微软雅黑")
        self.logout.setFont(font)
        self.logout.setObjectName("logout")
        self.groupBox_6 = QGroupBox(self.centralwidget)
        self.groupBox_6.setGeometry(QRect(10, 200, 231, 51))
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.linkStyle = QLabel(self.groupBox_6)
        self.linkStyle.setGeometry(QRect(10, 0, 71, 41))
        font = QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.linkStyle.setFont(font)
        self.linkStyle.setCursor(QCursor(Qt.ArrowCursor))
        self.linkStyle.setToolTip("")
        self.linkStyle.setAlignment(Qt.AlignCenter)
        self.linkStyle.setObjectName("linkStyle")
        self.comboBox = QComboBox(self.groupBox_6)
        self.comboBox.setGeometry(QRect(80, 10, 131, 26))
        font = QFont()
        font.setFamily("微软雅黑")
        self.comboBox.setFont(font)
        self.comboBox.setLayoutDirection(Qt.LeftToRight)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.user.setText(_translate("MainWindow", "用户名"))
        self.passwd.setText(_translate("MainWindow", "密  码"))
        self.passwdCB.setText(_translate("MainWindow", "记住密码"))
        self.auto_login.setText(_translate("MainWindow", "自动登录"))
        self.status_lable.setText(_translate("MainWindow", "连接状态"))
        self.updateLabel.setText(_translate("MainWindow", "关于 & 更新"))
        self.text.setText(_translate("MainWindow", "校 园 网"))
        self.login.setText(_translate("MainWindow", "连接 LogIn"))
        self.logout.setText(_translate("MainWindow", "下线"))
        self.linkStyle.setText(_translate("MainWindow", "连接方式"))
        self.comboBox.setItemText(0, _translate("MainWindow", "        请选择"))
        self.comboBox.setItemText(1, _translate("MainWindow", "       有线连接"))
        self.comboBox.setItemText(2, _translate("MainWindow", "       WIFI连接"))
