# -*- coding: utf-8 -*-

import sys, \
    os
if hasattr(sys, 'frozen'):
    os.environ['PATH'] = sys._MEIPASS + ";" + os.environ['PATH']

from PyQt5.QtWidgets import QWidget, QLabel, QHBoxLayout, QGroupBox, QGridLayout, QLineEdit, QPushButton, QTextBrowser, QCheckBox
from PyQt5.QtGui import QFont, QPixmap, QPalette, QColor, QCursor, QBrush
from PyQt5.QtCore import QRect, Qt, QMetaObject, QCoreApplication
import base64
from timg_png import img as timg
from linkSHUPath import shuPath


linkpath = shuPath()

sss = os.path.exists(linkpath + r'\timg.png')
if not sss:
    tmp = open(linkpath + r'\timg.png', 'wb')
    tmp.write(base64.b64decode(timg))
    tmp.close()
else:
    pass


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(391, 282)
        font = QFont()
        font.setPointSize(11)
        MainWindow.setFont(font)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QRect(10, 70, 231, 171))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget = QWidget(self.groupBox)
        self.gridLayoutWidget.setGeometry(QRect(9, 10, 213, 91))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.user = QLabel(self.gridLayoutWidget)
        font = QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.user.setFont(font)
        self.user.setAlignment(Qt.AlignCenter)
        self.user.setObjectName("user")
        self.gridLayout.addWidget(self.user, 0, 0, 1, 1)
        self.passwd = QLabel(self.gridLayoutWidget)
        font = QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.passwd.setFont(font)
        self.passwd.setAlignment(Qt.AlignCenter)
        self.passwd.setObjectName("passwd")
        self.gridLayout.addWidget(self.passwd, 1, 0, 1, 1)
        self.input_user = QLineEdit(self.gridLayoutWidget)
        font = QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.input_user.setFont(font)
        self.input_user.setText("")
        self.input_user.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.input_user.setObjectName("input_user")
        self.gridLayout.addWidget(self.input_user, 0, 1, 1, 1)
        self.input_passwd = QLineEdit(self.gridLayoutWidget)
        font = QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.input_passwd.setFont(font)
        self.input_passwd.setFocusPolicy(Qt.StrongFocus)
        self.input_passwd.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.input_passwd.setText("")
        self.input_passwd.setEchoMode(QLineEdit.Password)
        self.input_passwd.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.input_passwd.setObjectName("input_passwd")
        self.gridLayout.addWidget(self.input_passwd, 1, 1, 1, 1)
        self.horizontalLayoutWidget = QWidget(self.groupBox)
        self.horizontalLayoutWidget.setGeometry(QRect(10, 102, 211, 26))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_7 = QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.passwdCB = QCheckBox(self.horizontalLayoutWidget)
        font = QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.passwdCB.setFont(font)
        self.passwdCB.setObjectName("passwdCB")
        self.horizontalLayout_7.addWidget(self.passwdCB)
        self.auto_login = QCheckBox(self.horizontalLayoutWidget)
        font = QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.auto_login.setFont(font)
        self.auto_login.setObjectName("auto_login")
        self.horizontalLayout_7.addWidget(self.auto_login)
        self.horizontalLayoutWidget_3 = QWidget(self.groupBox)
        self.horizontalLayoutWidget_3.setGeometry(QRect(10, 130, 211, 31))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_2 = QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.wifiButton = QPushButton(self.horizontalLayoutWidget_3)
        font = QFont()
        font.setFamily("微软雅黑")
        self.wifiButton.setFont(font)
        self.wifiButton.setObjectName("wifiButton")
        self.horizontalLayout_2.addWidget(self.wifiButton)
        self.groupBox_2 = QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QRect(240, 70, 141, 171))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.status_lable = QLabel(self.groupBox_2)
        self.status_lable.setGeometry(QRect(30, 10, 71, 20))
        font = QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.status_lable.setFont(font)
        self.status_lable.setAlignment(Qt.AlignCenter)
        self.status_lable.setObjectName("status_lable")
        self.status = QTextBrowser(self.groupBox_2)
        self.status.setGeometry(QRect(10, 40, 121, 81))
        font = QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(7)
        self.status.setFont(font)
        self.status.setObjectName("status")
        self.logout = QPushButton(self.groupBox_2)
        self.logout.setGeometry(QRect(10, 130, 121, 28))
        font = QFont()
        font.setFamily("微软雅黑")
        self.logout.setFont(font)
        self.logout.setObjectName("logout")
        self.groupBox_3 = QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QRect(10, 240, 371, 31))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayoutWidget_2 = QWidget(self.groupBox_3)
        self.horizontalLayoutWidget_2.setGeometry(QRect(0, 0, 371, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_8 = QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.updateLabel = QLabel(self.horizontalLayoutWidget_2)
        font = QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.updateLabel.setFont(font)
        self.updateLabel.setCursor(QCursor(Qt.PointingHandCursor))
        self.updateLabel.setToolTip("")
        self.updateLabel.setAlignment(Qt.AlignCenter)
        self.updateLabel.setObjectName("updateLabel")
        self.horizontalLayout_8.addWidget(self.updateLabel)
        self.groupBox_4 = QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QRect(10, 10, 371, 61))
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.layoutWidget = QWidget(self.groupBox_4)
        self.layoutWidget.setGeometry(QRect(80, 10, 181, 43))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.logo = QLabel(self.layoutWidget)
        self.logo.setText("")
        self.logo.setPixmap(QPixmap(linkpath + r'\timg.png'))
        self.logo.setObjectName("logo")
        self.horizontalLayout.addWidget(self.logo)
        self.text = QLabel(self.layoutWidget)
        palette = QPalette()
        brush = QBrush(QColor(0, 85, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        brush = QBrush(QColor(0, 85, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush)
        brush = QBrush(QColor(120, 120, 120))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush)
        self.text.setPalette(palette)
        font = QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.text.setFont(font)
        self.text.setAlignment(Qt.AlignCenter)
        self.text.setObjectName("text")
        self.horizontalLayout.addWidget(self.text)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.user.setText(_translate("MainWindow", "用户名"))
        self.passwd.setText(_translate("MainWindow", "密  码"))
        self.passwdCB.setText(_translate("MainWindow", "记住密码"))
        self.auto_login.setText(_translate("MainWindow", "自动登录"))
        self.wifiButton.setText(_translate("MainWindow", "WIFI连接"))
        self.status_lable.setText(_translate("MainWindow", "连接状态"))
        self.logout.setText(_translate("MainWindow", "下线"))
        self.updateLabel.setText(_translate("MainWindow", "关于 & 更新"))
        self.text.setText(_translate("MainWindow", "校 园 网"))

